### ISSUE TITLE
“ Relational inductive biases, deep learning, and graph networks“ It might be proper to add it to the survey.

### ISSUE THREAD

**Issue by pobingwanghai** [jdlc105/Must-read-papers-and-continuous-tracking-on-Graph-Neural-Network-GNN-progress#2]
Appreciate your hard work!
For the newcomer to GNN, this paper is clear enough to explain how the graph network works.
For the experienced researchers, this paper is informative enough to make us think about which kinds of methods we can make to promote the GNN itself.

**Comment by jdlc105** [comment]
Thank you very much for your appreciation and good advice on my project.!
Yes, I quite agree with your proposal. After careful analysis, I have made adjustments to this in the latest update.

**Comment by pobingwanghai** [comment]
@jdlc105 Appreciate for your hard works!
